---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx

- name: Ensure nginx is running
  become: true
  ansible.builtin.systemd_service:
    name: nginx.service
    state: started
    enabled: true

- name: Disable default site
  become: true
  notify: Reload nginx
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create dummy site
  become: true
  vars:
    _j2_listen_ip: "{{ ansible_facts[external_interface]['ipv4']['address'] }}"
  ansible.builtin.template:
    src: etc/nginx/sites-available/dummy.j2
    dest: /etc/nginx/sites-available/dummy
    owner: root
    group: root
    mode: o=rw-,g=r--,o=r--

- name: Enable dummy site
  become: true
  notify: Reload nginx
  ansible.builtin.file:
    src: /etc/nginx/sites-available/dummy
    dest: /etc/nginx/sites-enabled/dummy
    state: link
    owner: root
    group: root
    mode: o=rw-,g=r--,o=r--
